sudo: false

language: bash

env:
  global:
    - GOBRANCH=master

script:
  - cd /tmp
  - bash -xe < <(curl -kL https://github.com/phuslu/goproxy/raw/master/assets/build/ci.sh)

branches:
  only:
    - master

addons:
  apt:
    packages:
      - p7zip-full
      - lftp
      - gcc-arm-linux-gnueabihf

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf18a3489def38eefa87
    on_success: always
    on_failure: always
    on_start: always
